# Generated by Django 6.0.7 on 2026-08-04 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plots', '0003_remove_plot_current_owner_plot_owner'),
        ('projects', '0007_grant_finance_and_sales_manager_view_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Survey companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('gross_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('road_reserve_area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('utility_reserve_area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('open_space_area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_saleable_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('road_type', models.CharField(choices=[('main', 'Main Road'), ('secondary', 'Secondary Road'), ('access', 'Access Road'), ('footpath', 'Footpath')], default='access', max_length=20)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('path_geojson', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='surveys.subdivision')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='scheduled', max_length=20)),
                ('coordinate_system', models.CharField(default='Arc 1960 / UTM Zone 37S', max_length=100)),
                ('area_surveyed_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.project')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='surveys.surveycompany')),
            ],
            options={
                'verbose_name_plural': 'Surveys',
                'ordering': ['-created_at'],
                'permissions': [('approve_survey', 'Can approve or reject a survey')],
            },
        ),
        migrations.AddField(
            model_name='subdivision',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='SurveyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('cad', 'CAD File'), ('gis', 'GIS File'), ('survey_map', 'Survey Map'), ('report', 'Survey Report'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='surveys/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='surveys.survey')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveyors', to='surveys.surveycompany')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveyor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='lead_surveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys_led', to='surveys.surveyor'),
        ),
        migrations.CreateModel(
            name='UtilityReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('sewer', 'Sewer'), ('storm_drainage', 'Storm Drainage'), ('telecom', 'Telecom'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('path_geojson', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='surveys.subdivision')),
            ],
            options={
                'ordering': ['utility_type'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_number', models.CharField(max_length=50)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=14)),
                ('land_use', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use'), ('open_space', 'Open Space')], default='residential', max_length=20)),
                ('corner_coordinates', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('plot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivision_plot', to='plots.plot')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_plots', to='surveys.subdivision')),
            ],
            options={
                'ordering': ['plot_number'],
                'constraints': [models.UniqueConstraint(fields=('subdivision', 'plot_number'), name='unique_planned_plot_number_per_subdivision')],
            },
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beacon_number', models.CharField(max_length=50)),
                ('beacon_type', models.CharField(choices=[('concrete_pillar', 'Concrete Pillar'), ('iron_pin', 'Iron Pin'), ('wooden_peg', 'Wooden Peg'), ('other', 'Other')], default='concrete_pillar', max_length=20)),
                ('condition', models.CharField(choices=[('intact', 'Intact'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='intact', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('easting', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('northing', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='surveys.survey')),
            ],
            options={
                'ordering': ['beacon_number'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'beacon_number'), name='unique_beacon_number_per_survey')],
            },
        ),
    ]
