import uuid

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone

from apps.core.models import BaseModel
from apps.sales.models import Sale

# None of these models carry their own FileField — the scanned/signed copy of
# a title deed, agreement, POA, contract or template attaches through the
# Documents module instead (content_type='legal.<model>', object_id=this
# row's id), which gives every legal record versioning + audit trail for free.


def _generate_number(prefix):
    return f'{prefix}-{timezone.now():%Y%m}-{uuid.uuid4().hex[:8].upper()}'


class SaleAgreement(BaseModel):
    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        SENT_FOR_SIGNATURE = 'sent_for_signature', 'Sent for Signature'
        SIGNED = 'signed', 'Signed'
        APPROVED = 'approved', 'Approved'
        VOID = 'void', 'Void'

    sale = models.OneToOneField(Sale, on_delete=models.CASCADE, related_name='sale_agreement')
    agreement_number = models.CharField(max_length=30, unique=True, editable=False, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.DRAFT)
    terms = models.TextField(blank=True)
    signed_date = models.DateField(null=True, blank=True)
    prepared_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='sale_agreements_prepared',
    )

    # Approval workflow — a signed agreement still needs sign-off (Legal
    # Officer/Managing Director) before it's binding; voiding is gated too.
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='sale_agreements_approved',
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    voided_at = models.DateTimeField(null=True, blank=True)
    void_reason = models.TextField(blank=True)

    class Meta:
        ordering = ['-created_at']
        permissions = [
            ('approve_saleagreement', 'Can approve or void a sale agreement'),
        ]

    def __str__(self):
        return f'{self.agreement_number} - {self.sale.sale_number}'

    def save(self, *args, **kwargs):
        if not self.agreement_number:
            self.agreement_number = _generate_number('AGR')
        super().save(*args, **kwargs)


class TitleDeed(BaseModel):
    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        APPLIED = 'applied', 'Applied at Registry'
        ISSUED = 'issued', 'Issued'
        APPROVED = 'approved', 'Approved'

    sale = models.OneToOneField(Sale, on_delete=models.CASCADE, related_name='title_deed')
    # Assigned by the Land Registry, not generated by us — blank until issued.
    deed_number = models.CharField(max_length=50, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    registry_office = models.CharField(max_length=255, blank=True)
    applied_date = models.DateField(null=True, blank=True)
    issued_date = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    # Approval workflow — an issued deed still needs Legal to verify its
    # details against the sale before it's filed as approved.
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='title_deeds_approved',
    )
    approved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        permissions = [
            ('approve_titledeed', 'Can approve an issued title deed'),
        ]

    def __str__(self):
        return f'Title deed for {self.sale.sale_number}'


class PowerOfAttorney(BaseModel):
    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        ACTIVE = 'active', 'Active'
        EXPIRED = 'expired', 'Expired'
        REVOKED = 'revoked', 'Revoked'

    poa_number = models.CharField(max_length=30, unique=True, editable=False, blank=True)
    sale = models.ForeignKey(
        Sale, null=True, blank=True, on_delete=models.SET_NULL, related_name='powers_of_attorney',
    )
    grantor_name = models.CharField(max_length=255)
    grantee_name = models.CharField(max_length=255)
    # A POA grants real legal authority, so it starts Pending and only
    # becomes Active once approved — never active by default.
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    granted_date = models.DateField(null=True, blank=True)
    expiry_date = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    # Approval workflow — activation and revocation both need sign-off.
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='powers_of_attorney_approved',
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    revocation_reason = models.TextField(blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Power of attorney'
        verbose_name_plural = 'Powers of attorney'
        permissions = [
            ('approve_powerofattorney', 'Can approve (activate) or revoke a power of attorney'),
        ]

    def __str__(self):
        return f'{self.poa_number} - {self.grantor_name} to {self.grantee_name}'

    def save(self, *args, **kwargs):
        if not self.poa_number:
            self.poa_number = _generate_number('POA')
        super().save(*args, **kwargs)


class Contract(BaseModel):
    class ContractType(models.TextChoices):
        SERVICE = 'service', 'Service Agreement'
        VENDOR = 'vendor', 'Vendor Agreement'
        EMPLOYMENT = 'employment', 'Employment Contract'
        PARTNERSHIP = 'partnership', 'Partnership Agreement'
        OTHER = 'other', 'Other'

    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        ACTIVE = 'active', 'Active'
        EXPIRED = 'expired', 'Expired'
        TERMINATED = 'terminated', 'Terminated'

    contract_number = models.CharField(max_length=30, unique=True, editable=False, blank=True)
    title = models.CharField(max_length=255)
    contract_type = models.CharField(max_length=20, choices=ContractType.choices, default=ContractType.OTHER)
    counterparty_name = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.DRAFT)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    # Optional link to whatever this contract concerns (a SurveyCompany, a
    # Project, ...) — generic so Legal doesn't need a new FK per module.
    content_type = models.ForeignKey(
        ContentType, null=True, blank=True, on_delete=models.SET_NULL, related_name='legal_contracts',
    )
    object_id = models.CharField(max_length=255, blank=True, default='')
    content_object = GenericForeignKey('content_type', 'object_id')

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='contracts_created',
    )

    class Meta:
        ordering = ['-created_at']
        indexes = [models.Index(fields=['content_type', 'object_id'])]

    def __str__(self):
        return f'{self.contract_number} - {self.title}'

    def save(self, *args, **kwargs):
        if not self.contract_number:
            self.contract_number = _generate_number('CTR')
        super().save(*args, **kwargs)


class OwnershipTransfer(BaseModel):
    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        APPROVED = 'approved', 'Approved'
        COMPLETED = 'completed', 'Completed'
        REJECTED = 'rejected', 'Rejected'

    sale = models.OneToOneField(Sale, on_delete=models.CASCADE, related_name='ownership_transfer')
    transfer_number = models.CharField(max_length=30, unique=True, editable=False, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)

    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='ownership_transfers_requested',
    )
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='ownership_transfers_approved',
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    # Set when the transfer is executed — the same moment the plot flips to
    # Transferred and legal staff are notified.
    completed_at = models.DateTimeField(null=True, blank=True)
    rejection_reason = models.TextField(blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['-created_at']
        permissions = [
            ('approve_ownershiptransfer', 'Can approve, complete, or reject an ownership transfer'),
        ]

    def __str__(self):
        return f'{self.transfer_number} - {self.sale.sale_number}'

    def save(self, *args, **kwargs):
        if not self.transfer_number:
            self.transfer_number = _generate_number('OT')
        super().save(*args, **kwargs)


class Witness(BaseModel):
    # Generic link to whichever legal record this witness signed for — a
    # SaleAgreement, PowerOfAttorney, Contract, or OwnershipTransfer.
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, related_name='witnesses')
    object_id = models.CharField(max_length=255)
    content_object = GenericForeignKey('content_type', 'object_id')

    full_name = models.CharField(max_length=255)
    national_id = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    signed_at = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['full_name']
        indexes = [models.Index(fields=['content_type', 'object_id'])]

    def __str__(self):
        return self.full_name


class DocumentTemplate(BaseModel):
    class TemplateType(models.TextChoices):
        SALE_AGREEMENT = 'sale_agreement', 'Sale Agreement'
        TITLE_DEED = 'title_deed', 'Title Deed'
        POWER_OF_ATTORNEY = 'power_of_attorney', 'Power of Attorney'
        CONTRACT = 'contract', 'Contract'
        OTHER = 'other', 'Other'

    name = models.CharField(max_length=255)
    template_type = models.CharField(max_length=20, choices=TemplateType.choices, default=TemplateType.OTHER)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='document_templates_created',
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
