# Generated by Django 6.0.7 on 2026-08-04 13:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_grant_finance_and_sales_manager_view_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('potential', 'Potential'), ('negotiating', 'Negotiating'), ('approved', 'Approved'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='potential', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('legal_checks_passed', models.BooleanField(default=False)),
                ('due_diligence_notes', models.TextField(blank=True)),
                ('valuation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('valuator_name', models.CharField(blank=True, max_length=255)),
                ('asking_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_landacquisition', 'Can approve, mark purchased, or cancel a land acquisition')],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('survey_map', 'Survey Map'), ('id_copy', 'ID Copy'), ('agreement', 'Agreement'), ('valuation_report', 'Valuation Report'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='acquisitions/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_attachments', to=settings.AUTH_USER_MODEL)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='acquisitions.landacquisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='acquisitions.landacquisition')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negotiated_on', models.DateField(default=django.utils.timezone.now)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counter_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='acquisitions.landacquisition')),
                ('negotiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiations_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-negotiated_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(choices=[('legal_fees', 'Legal Fees'), ('survey_fees', 'Survey Fees'), ('agent_commission', 'Agent Commission'), ('stamp_duty', 'Stamp Duty'), ('transfer_fees', 'Transfer Fees'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('incurred_on', models.DateField(default=django.utils.timezone.now)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_costs', to='acquisitions.landacquisition')),
            ],
            options={
                'ordering': ['-incurred_on'],
            },
        ),
    ]
