# Generated by Django 6.0.7 on 2026-08-04 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0002_grant_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='negotiated_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='purchasecost',
            name='incurred_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
