# Generated by Django 6.0.7 on 2026-07-29 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('development', 'Development'), ('selling', 'Selling'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('master_plan_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('video_urls', models.JSONField(blank=True, default=list)),
                ('nearby_services', models.JSONField(blank=True, default=list)),
                ('total_area_sqm', models.DecimalField(decimal_places=2, max_digits=14)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('development_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
