# Generated by Django 6.0.7 on 2026-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('view_project_financials', 'Can view project financial figures (expected revenue, ROI)')]},
        ),
    ]
