# Generated by Django 6.0.7 on 2026-07-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_grant_sales_agent_view_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
