# Generated by Django 6.0.7 on 2026-08-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('installment_due_reminder', 'Installment Due Reminder'), ('installment_overdue_alert', 'Installment Overdue Alert'), ('ownership_transfer_completed', 'Ownership Transfer Completed')], max_length=50),
        ),
    ]
