from datetime import date
from decimal import Decimal

import pytest
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APIClient

from apps.accounts.models import Role, User

from .models import Attendance, Department, Employee, LeaveRequest, LeaveType, PayrollRecord, PerformanceReview


@pytest.fixture
def api_client():
    return APIClient()


@pytest.fixture
def managing_director_role(db):
    return Role.objects.get(name='Managing Director')


@pytest.fixture
def finance_manager_role(db):
    return Role.objects.get(name='Finance Manager')


@pytest.fixture
def sales_agent_role(db):
    # Not granted any hr permissions in the seeding migration.
    return Role.objects.get(name='Sales Agent')


@pytest.fixture
def managing_director(db, managing_director_role):
    return User.objects.create_user(
        email='md@landflow.co.tz', password='s3cure-pass', role=managing_director_role,
    )


@pytest.fixture
def finance_manager(db, finance_manager_role):
    return User.objects.create_user(
        email='finance@landflow.co.tz', password='s3cure-pass', role=finance_manager_role,
    )


@pytest.fixture
def sales_agent(db, sales_agent_role):
    return User.objects.create_user(email='agent@landflow.co.tz', password='s3cure-pass', role=sales_agent_role)


@pytest.fixture
def department(db):
    return Department.objects.create(name='Sales')


@pytest.fixture
def employee(db, department):
    return Employee.objects.create(
        full_name='Amina Suleiman', job_title='Sales Executive', department=department,
        basic_salary=Decimal('1500000.00'),
    )


@pytest.fixture
def leave_type(db):
    return LeaveType.objects.create(name='Annual Leave', default_days_per_year=28)


@pytest.fixture
def leave_request(db, employee, leave_type):
    return LeaveRequest.objects.create(
        employee=employee, leave_type=leave_type, start_date=date(2026, 9, 1), end_date=date(2026, 9, 5),
    )


@pytest.fixture
def payroll_record(db, employee):
    return PayrollRecord.objects.create(
        employee=employee, pay_period_start='2026-08-01', pay_period_end='2026-08-31',
        basic_salary=Decimal('1500000.00'), allowances=Decimal('100000.00'), deductions=Decimal('50000.00'),
    )


@pytest.mark.django_db
def test_employee_number_is_autogenerated(employee):
    assert employee.employee_number.startswith('EMP-')


@pytest.mark.django_db
def test_department_manager_can_be_an_employee(department, employee):
    department.manager = employee
    department.save(update_fields=['manager'])
    department.refresh_from_db()
    assert department.manager_id == employee.id


@pytest.mark.django_db
def test_leave_request_requested_days(leave_request):
    assert leave_request.requested_days == 5


@pytest.mark.django_db
def test_payroll_net_pay(payroll_record):
    assert payroll_record.net_pay == Decimal('1550000.00')


@pytest.mark.django_db
def test_list_requires_authentication(api_client):
    response = api_client.get(reverse('employee-list'))
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


@pytest.mark.django_db
def test_role_without_permission_gets_403(api_client, sales_agent, employee):
    api_client.force_authenticate(user=sales_agent)
    response = api_client.get(reverse('employee-list'))
    assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
def test_managing_director_can_create_employee(api_client, managing_director, department):
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(reverse('employee-list'), {
        'full_name': 'John Mnyika', 'department': str(department.id),
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data
    created = Employee.objects.get(id=response.data['id'])
    assert created.employee_number.startswith('EMP-')


@pytest.mark.django_db
def test_status_field_is_read_only_on_update(api_client, managing_director, employee):
    api_client.force_authenticate(user=managing_director)
    response = api_client.patch(reverse('employee-detail', args=[employee.id]), {'status': 'terminated'})
    assert response.status_code == status.HTTP_200_OK
    employee.refresh_from_db()
    assert employee.status == Employee.Status.ACTIVE


@pytest.mark.django_db
def test_employee_lifecycle_actions(api_client, managing_director, employee):
    api_client.force_authenticate(user=managing_director)

    response = api_client.post(reverse('employee-put-on-leave', args=[employee.id]))
    assert response.status_code == status.HTTP_200_OK
    employee.refresh_from_db()
    assert employee.status == Employee.Status.ON_LEAVE

    response = api_client.post(reverse('employee-activate', args=[employee.id]))
    assert response.status_code == status.HTTP_200_OK
    employee.refresh_from_db()
    assert employee.status == Employee.Status.ACTIVE

    response = api_client.post(reverse('employee-suspend', args=[employee.id]))
    assert response.status_code == status.HTTP_200_OK
    employee.refresh_from_db()
    assert employee.status == Employee.Status.SUSPENDED

    response = api_client.post(reverse('employee-terminate', args=[employee.id]))
    assert response.status_code == status.HTTP_200_OK
    employee.refresh_from_db()
    assert employee.status == Employee.Status.TERMINATED
    assert employee.termination_date is not None

    response = api_client.post(reverse('employee-suspend', args=[employee.id]))
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_finance_manager_cannot_create_employee(api_client, finance_manager, department):
    api_client.force_authenticate(user=finance_manager)
    response = api_client.post(reverse('employee-list'), {
        'full_name': 'John Mnyika', 'department': str(department.id),
    })
    assert response.status_code == status.HTTP_403_FORBIDDEN


# ---------------------------------------------------------------------------
# Leave requests
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_leave_request_approve_reject_gated_by_dedicated_permission(api_client, finance_manager, leave_request):
    # Finance Manager can view leave requests but does not hold approve_leaverequest.
    api_client.force_authenticate(user=finance_manager)
    response = api_client.post(reverse('leaverequest-approve', args=[leave_request.id]))
    assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
def test_managing_director_can_approve_leave_request(api_client, managing_director, leave_request):
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(reverse('leaverequest-approve', args=[leave_request.id]))
    assert response.status_code == status.HTTP_200_OK
    leave_request.refresh_from_db()
    assert leave_request.status == LeaveRequest.Status.APPROVED
    assert leave_request.approved_by_id == managing_director.id
    assert leave_request.approved_at is not None


@pytest.mark.django_db
def test_managing_director_can_reject_leave_request_with_reason(api_client, managing_director, leave_request):
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(
        reverse('leaverequest-reject', args=[leave_request.id]), {'rejection_reason': 'Peak season'},
    )
    assert response.status_code == status.HTTP_200_OK
    leave_request.refresh_from_db()
    assert leave_request.status == LeaveRequest.Status.REJECTED
    assert leave_request.rejection_reason == 'Peak season'


@pytest.mark.django_db
def test_approve_rejects_non_pending_leave_request(api_client, managing_director, leave_request):
    leave_request.status = LeaveRequest.Status.CANCELLED
    leave_request.save(update_fields=['status'])
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(reverse('leaverequest-approve', args=[leave_request.id]))
    assert response.status_code == status.HTTP_400_BAD_REQUEST


# ---------------------------------------------------------------------------
# Attendance
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_attendance_unique_per_employee_per_day(employee):
    Attendance.objects.create(employee=employee, date='2026-08-17', status=Attendance.Status.PRESENT)
    with pytest.raises(Exception):
        Attendance.objects.create(employee=employee, date='2026-08-17', status=Attendance.Status.LATE)


@pytest.mark.django_db
def test_managing_director_can_record_attendance(api_client, managing_director, employee):
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(reverse('attendance-list'), {
        'employee': str(employee.id), 'date': '2026-08-17', 'status': Attendance.Status.PRESENT,
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data


# ---------------------------------------------------------------------------
# Performance reviews
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_performance_review_sets_reviewer_from_request_user(api_client, managing_director, employee):
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(reverse('performancereview-list'), {
        'employee': str(employee.id), 'review_period_start': '2026-01-01', 'review_period_end': '2026-06-30',
        'rating': 4,
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data
    review = PerformanceReview.objects.get(id=response.data['id'])
    assert review.reviewer_id == managing_director.id


# ---------------------------------------------------------------------------
# Payroll
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_payroll_unique_per_employee_per_period(employee):
    PayrollRecord.objects.create(
        employee=employee, pay_period_start='2026-08-01', pay_period_end='2026-08-31',
        basic_salary=Decimal('1500000.00'),
    )
    with pytest.raises(Exception):
        PayrollRecord.objects.create(
            employee=employee, pay_period_start='2026-08-01', pay_period_end='2026-08-31',
            basic_salary=Decimal('1500000.00'),
        )


@pytest.mark.django_db
def test_finance_manager_process_and_mark_paid_workflow(api_client, finance_manager, payroll_record):
    api_client.force_authenticate(user=finance_manager)

    response = api_client.post(reverse('payrollrecord-mark-paid', args=[payroll_record.id]))
    assert response.status_code == status.HTTP_400_BAD_REQUEST

    response = api_client.post(reverse('payrollrecord-process', args=[payroll_record.id]))
    assert response.status_code == status.HTTP_200_OK
    payroll_record.refresh_from_db()
    assert payroll_record.status == PayrollRecord.Status.PROCESSED
    assert payroll_record.processed_at is not None

    response = api_client.post(reverse('payrollrecord-mark-paid', args=[payroll_record.id]))
    assert response.status_code == status.HTTP_200_OK
    payroll_record.refresh_from_db()
    assert payroll_record.status == PayrollRecord.Status.PAID
    assert payroll_record.paid_at is not None
