from decimal import Decimal

import pytest
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APIClient

from apps.accounts.models import Role, User
from apps.crm.models import Customer
from apps.hr.models import Employee
from apps.plots.models import Plot
from apps.projects.models import Project
from apps.sales.models import Sale

from .models import Agent, CommissionPayment, CommissionPlan, CommissionTier, SalesTarget, Territory


@pytest.fixture
def api_client():
    return APIClient()


@pytest.fixture
def managing_director_role(db):
    return Role.objects.get(name='Managing Director')


@pytest.fixture
def sales_manager_role(db):
    return Role.objects.get(name='Sales Manager')


@pytest.fixture
def sales_agent_role(db):
    return Role.objects.get(name='Sales Agent')


@pytest.fixture
def managing_director(db, managing_director_role):
    return User.objects.create_user(email='md@landflow.co.tz', password='s3cure-pass', role=managing_director_role)


@pytest.fixture
def sales_manager(db, sales_manager_role):
    return User.objects.create_user(
        email='salesmanager@landflow.co.tz', password='s3cure-pass', role=sales_manager_role,
    )


@pytest.fixture
def sales_agent_user(db, sales_agent_role):
    return User.objects.create_user(email='agent@landflow.co.tz', password='s3cure-pass', role=sales_agent_role)


@pytest.fixture
def employee(db, sales_agent_user):
    return Employee.objects.create(full_name='Halima Juma', user=sales_agent_user)


@pytest.fixture
def territory(db):
    return Territory.objects.create(name='Dar es Salaam Central')


@pytest.fixture
def commission_plan(db):
    return CommissionPlan.objects.create(
        name='Standard 3%', plan_type=CommissionPlan.PlanType.PERCENTAGE, rate_percent=Decimal('3.00'),
    )


@pytest.fixture
def agent(db, employee, territory, commission_plan):
    return Agent.objects.create(employee=employee, territory=territory, commission_plan=commission_plan)


@pytest.fixture
def project(db):
    return Project.objects.create(
        name='Buyuni Phase II', location='Buyuni, Dar es Salaam', total_area_sqm=Decimal('50000.00'),
    )


@pytest.fixture
def plot(db, project):
    return Plot.objects.create(
        project=project, plot_number='A-01', area_sqm=Decimal('500.00'), price=Decimal('20000000.00'),
    )


@pytest.fixture
def customer(db):
    return Customer.objects.create(full_name='Juma Hassan', phone='+255700000000')


@pytest.mark.django_db
def test_agent_code_is_autogenerated(agent):
    assert agent.agent_code.startswith('AGT-')


@pytest.mark.django_db
def test_agent_str_delegates_to_employee_name(agent, employee):
    assert employee.full_name in str(agent)


@pytest.mark.django_db
def test_commission_plan_percentage_calculation(commission_plan):
    assert commission_plan.calculate_commission(Decimal('20000000.00')) == Decimal('600000.00')


@pytest.mark.django_db
def test_commission_plan_flat_calculation():
    plan = CommissionPlan.objects.create(
        name='Flat Plan', plan_type=CommissionPlan.PlanType.FLAT, flat_amount=Decimal('250000.00'),
    )
    assert plan.calculate_commission(Decimal('99999999.00')) == Decimal('250000.00')


@pytest.mark.django_db
def test_commission_plan_tiered_calculation():
    plan = CommissionPlan.objects.create(name='Tiered Plan', plan_type=CommissionPlan.PlanType.TIERED)
    CommissionTier.objects.create(
        plan=plan, min_amount=Decimal('0'), max_amount=Decimal('10000000'), rate_percent=Decimal('2.00'),
    )
    CommissionTier.objects.create(
        plan=plan, min_amount=Decimal('10000000.01'), max_amount=None, rate_percent=Decimal('4.00'),
    )

    assert plan.calculate_commission(Decimal('5000000.00')) == Decimal('100000.00')
    assert plan.calculate_commission(Decimal('20000000.00')) == Decimal('800000.00')


@pytest.mark.django_db
def test_inactive_plan_calculates_zero_commission(commission_plan):
    commission_plan.is_active = False
    commission_plan.save(update_fields=['is_active'])
    assert commission_plan.calculate_commission(Decimal('20000000.00')) == Decimal('0.00')


# ---------------------------------------------------------------------------
# Auto-commission on sale (Sale -> Employee -> Agent chain)
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_sale_by_agent_auto_creates_commission_payment(api_client, sales_agent_user, agent, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=sales_agent_user)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data

    sale = Sale.objects.get(id=response.data['id'])
    payment = CommissionPayment.objects.get(sale=sale)
    assert payment.agent_id == agent.id
    assert payment.amount == Decimal('600000.00')
    assert payment.status == CommissionPayment.Status.PENDING


@pytest.mark.django_db
def test_sale_by_non_agent_user_does_not_create_commission_payment(api_client, managing_director, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=managing_director)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data
    sale = Sale.objects.get(id=response.data['id'])
    assert not CommissionPayment.objects.filter(sale=sale).exists()


# ---------------------------------------------------------------------------
# Sales targets
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_sales_target_achieved_amount_tracks_agents_closed_sales(sales_agent_user, agent, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    Sale.objects.create(
        plot=plot, customer=customer, sale_type=Sale.SaleType.CASH,
        sale_price=Decimal('20000000.00'), down_payment=Decimal('20000000.00'), sold_by=sales_agent_user,
    )
    target = SalesTarget.objects.create(
        agent=agent, period_start='2026-01-01', period_end='2026-12-31', target_amount=Decimal('50000000.00'),
    )
    assert target.achieved_amount == Decimal('20000000.00')
    assert target.achieved_plot_count == 1


# ---------------------------------------------------------------------------
# API permissions and commission-payment workflow
# ---------------------------------------------------------------------------

@pytest.mark.django_db
def test_list_requires_authentication(api_client):
    response = api_client.get(reverse('agent-list'))
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


@pytest.mark.django_db
def test_sales_manager_can_create_agent(api_client, sales_manager, employee, territory, commission_plan):
    api_client.force_authenticate(user=sales_manager)
    response = api_client.post(reverse('agent-list'), {
        'employee': str(employee.id), 'territory': str(territory.id), 'commission_plan': str(commission_plan.id),
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data
    assert response.data['agent_code'].startswith('AGT-')


@pytest.mark.django_db
def test_sales_agent_cannot_create_agent(api_client, sales_agent_user, employee, territory, commission_plan):
    api_client.force_authenticate(user=sales_agent_user)
    response = api_client.post(reverse('agent-list'), {
        'employee': str(employee.id), 'territory': str(territory.id), 'commission_plan': str(commission_plan.id),
    })
    assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
def test_commission_payment_approve_gated_by_dedicated_permission(api_client, sales_manager, agent):
    payment = CommissionPayment.objects.create(agent=agent, amount=Decimal('600000.00'))
    api_client.force_authenticate(user=sales_manager)
    response = api_client.post(reverse('commissionpayment-approve', args=[payment.id]))
    assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
def test_managing_director_commission_payment_approve_paid_workflow(api_client, managing_director, agent):
    payment = CommissionPayment.objects.create(agent=agent, amount=Decimal('600000.00'))
    api_client.force_authenticate(user=managing_director)

    response = api_client.post(reverse('commissionpayment-mark-paid', args=[payment.id]))
    assert response.status_code == status.HTTP_400_BAD_REQUEST

    response = api_client.post(reverse('commissionpayment-approve', args=[payment.id]))
    assert response.status_code == status.HTTP_200_OK
    payment.refresh_from_db()
    assert payment.status == CommissionPayment.Status.APPROVED
    assert payment.approved_by_id == managing_director.id

    response = api_client.post(
        reverse('commissionpayment-mark-paid', args=[payment.id]), {'payment_reference': 'TXN-001'},
    )
    assert response.status_code == status.HTTP_200_OK
    payment.refresh_from_db()
    assert payment.status == CommissionPayment.Status.PAID
    assert payment.payment_reference == 'TXN-001'


@pytest.mark.django_db
def test_paid_commission_payment_cannot_be_cancelled(api_client, managing_director, agent):
    payment = CommissionPayment.objects.create(
        agent=agent, amount=Decimal('600000.00'), status=CommissionPayment.Status.PAID,
    )
    api_client.force_authenticate(user=managing_director)
    response = api_client.post(reverse('commissionpayment-cancel', args=[payment.id]))
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_rankings_orders_agents_by_approved_and_paid_commission(api_client, managing_director, agent):
    CommissionPayment.objects.create(agent=agent, amount=Decimal('600000.00'), status=CommissionPayment.Status.APPROVED)
    CommissionPayment.objects.create(agent=agent, amount=Decimal('100000.00'), status=CommissionPayment.Status.PENDING)
    api_client.force_authenticate(user=managing_director)

    response = api_client.get(reverse('agent-rankings'))
    assert response.status_code == status.HTTP_200_OK
    assert response.data[0]['id'] == str(agent.id)
    assert Decimal(response.data[0]['total_commission']) == Decimal('600000.00')
    assert response.data[0]['sale_count'] == 1
    assert response.data[0]['rank'] == 1
