# Generated by Django 6.0.7 on 2026-08-01 14:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CashBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('petty_cash', 'Petty Cash')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(limit_choices_to={'type': 'asset'}, on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank_account', to='finance.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sale', 'Sale'), ('installment', 'Installment'), ('system', 'System')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('payee', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='finance.account')),
                ('paid_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='finance.cashbankaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='finance.journalentry')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget')),
            ],
            options={
                'ordering': ['budget', 'account'],
                'constraints': [models.UniqueConstraint(fields=('budget', 'account'), name='unique_budget_line_per_account')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('sale', 'Sale Receipt'), ('installment', 'Installment Payment'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(limit_choices_to={'type': 'income'}, on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='finance.account')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('deposit_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='finance.cashbankaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_recorded', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='finance.journalentry')),
            ],
            options={
                'verbose_name_plural': 'Income',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('object_id', ''), _negated=True), fields=('content_type', 'object_id'), name='unique_income_source_object')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'ordering': ['journal_entry', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journal_line_not_both_debit_and_credit'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='journal_line_debit_or_credit_required')],
            },
        ),
    ]
