# Generated by Django 6.0.7 on 2026-07-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_grant_crm_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='national_id',
        ),
    ]
