# Generated by Django 6.0.7 on 2026-07-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_customer_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.TextField(blank=True),
        ),
    ]
