from datetime import timedelta
from decimal import Decimal

import pytest
from django.urls import reverse
from django.utils import timezone
from rest_framework import status
from rest_framework.test import APIClient

from apps.accounts.models import Role, User
from apps.crm.models import Customer
from apps.plots.models import Plot
from apps.projects.models import Project
from apps.reservations.models import Reservation

from .models import Sale


@pytest.fixture(autouse=True)
def media_root(settings, tmp_path):
    # Keep the stub PDFs generated during tests out of the real media/ dir.
    settings.MEDIA_ROOT = tmp_path


@pytest.fixture
def api_client():
    return APIClient()


@pytest.fixture
def sales_agent_role(db):
    return Role.objects.get(name='Sales Agent')


@pytest.fixture
def finance_manager_role(db):
    return Role.objects.get(name='Finance Manager')


@pytest.fixture
def customer_role(db):
    # Not granted any sales permissions in the seeding migration.
    return Role.objects.get(name='Customer')


@pytest.fixture
def agent(db, sales_agent_role):
    return User.objects.create_user(
        email='agent@landflow.co.tz', password='s3cure-pass', role=sales_agent_role,
    )


@pytest.fixture
def finance_manager(db, finance_manager_role):
    return User.objects.create_user(
        email='finance@landflow.co.tz', password='s3cure-pass', role=finance_manager_role,
    )


@pytest.fixture
def customer_user(db, customer_role):
    return User.objects.create_user(
        email='customer@landflow.co.tz', password='s3cure-pass', role=customer_role,
    )


@pytest.fixture
def project(db):
    return Project.objects.create(
        name='Buyuni Phase II', location='Buyuni, Dar es Salaam', total_area_sqm=Decimal('50000.00'),
    )


@pytest.fixture
def plot(db, project):
    return Plot.objects.create(
        project=project, plot_number='A-01', area_sqm=Decimal('500.00'), price=Decimal('20000000.00'),
    )


@pytest.fixture
def customer(db):
    return Customer.objects.create(full_name='Juma Hassan', phone='+255700000000')


@pytest.fixture
def sale(db, plot, customer):
    return Sale.objects.create(
        plot=plot, customer=customer, sale_type=Sale.SaleType.CASH,
        sale_price=Decimal('20000000.00'), down_payment=Decimal('20000000.00'),
    )


@pytest.mark.django_db
def test_str_includes_sale_number_plot_and_customer(sale):
    assert sale.sale_number in str(sale)
    assert str(sale.plot) in str(sale)
    assert str(sale.customer) in str(sale)


@pytest.mark.django_db
def test_sale_number_is_autogenerated(sale):
    assert sale.sale_number.startswith('SALE-')


@pytest.mark.django_db
def test_net_price_and_balance_due(plot, customer):
    sale = Sale.objects.create(
        plot=plot, customer=customer, sale_type=Sale.SaleType.INSTALLMENT,
        sale_price=Decimal('20000000.00'), discount=Decimal('1000000.00'), down_payment=Decimal('5000000.00'),
    )
    assert sale.net_price == Decimal('19000000.00')
    assert sale.balance_due == Decimal('14000000.00')


@pytest.mark.django_db
def test_only_one_active_sale_per_plot(plot, customer):
    Sale.objects.create(
        plot=plot, customer=customer, sale_type=Sale.SaleType.CASH,
        sale_price=Decimal('20000000.00'), down_payment=Decimal('20000000.00'),
    )
    with pytest.raises(Exception):
        Sale.objects.create(
            plot=plot, customer=customer, sale_type=Sale.SaleType.CASH,
            sale_price=Decimal('20000000.00'), down_payment=Decimal('20000000.00'),
        )


@pytest.mark.django_db
def test_list_requires_authentication(api_client):
    response = api_client.get(reverse('sale-list'))
    assert response.status_code == status.HTTP_401_UNAUTHORIZED


@pytest.mark.django_db
def test_role_without_permission_gets_403(api_client, customer_user, sale):
    api_client.force_authenticate(user=customer_user)
    response = api_client.get(reverse('sale-list'))
    assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
def test_finance_manager_can_view_but_not_create(api_client, finance_manager, sale, plot, customer):
    api_client.force_authenticate(user=finance_manager)
    response = api_client.get(reverse('sale-list'))
    assert response.status_code == status.HTTP_200_OK
    assert response.data['count'] == 1

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_403_FORBIDDEN


@pytest.mark.django_db
def test_direct_cash_sale_marks_plot_sold_and_generates_documents(api_client, agent, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'cash',
    })

    assert response.status_code == status.HTTP_201_CREATED, response.data
    plot.refresh_from_db()
    assert plot.status == Plot.Status.SOLD
    assert plot.owner_id == customer.id

    sale = Sale.objects.get(pk=response.data['id'])
    assert sale.sold_by_id == agent.id
    assert hasattr(sale, 'invoice')
    assert sale.invoice.amount == sale.net_price
    assert sale.invoice.file.name
    assert sale.receipts.count() == 1
    receipt = sale.receipts.first()
    assert receipt.amount == sale.down_payment
    assert receipt.file.name


@pytest.mark.django_db
def test_direct_sale_rejects_plot_that_is_not_available(api_client, agent, plot, customer):
    plot.status = Plot.Status.SOLD
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_cash_sale_requires_full_down_payment(api_client, agent, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '5000000.00', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_400_BAD_REQUEST
    assert 'down_payment' in response.data


@pytest.mark.django_db
def test_installment_sale_allows_partial_down_payment(api_client, agent, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.INSTALLMENT,
        'sale_price': '20000000.00', 'down_payment': '5000000.00', 'payment_method': 'mobile_money',
    })
    assert response.status_code == status.HTTP_201_CREATED, response.data
    assert Decimal(response.data['balance_due']) == Decimal('15000000.00')


@pytest.mark.django_db
def test_down_payment_must_be_greater_than_zero(api_client, agent, plot, customer):
    plot.status = Plot.Status.AVAILABLE
    plot.save(update_fields=['status'])
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'plot': str(plot.id), 'customer': str(customer.id), 'sale_type': Sale.SaleType.INSTALLMENT,
        'sale_price': '20000000.00', 'down_payment': '0', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_sale_from_reservation_marks_reservation_converted(api_client, agent, plot, customer):
    plot.status = Plot.Status.RESERVED
    plot.save(update_fields=['status'])
    reservation = Reservation.objects.create(
        plot=plot, customer=customer, reservation_fee=Decimal('100000.00'),
        expiry_date=timezone.now() + timedelta(days=7),
    )
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'reservation': str(reservation.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'bank_transfer',
    })

    assert response.status_code == status.HTTP_201_CREATED, response.data
    reservation.refresh_from_db()
    plot.refresh_from_db()
    assert reservation.status == Reservation.Status.CONVERTED
    assert reservation.converted_at is not None
    assert plot.status == Plot.Status.SOLD
    assert plot.owner_id == customer.id


@pytest.mark.django_db
def test_sale_from_non_active_reservation_is_rejected(api_client, agent, plot, customer):
    plot.status = Plot.Status.RESERVED
    plot.save(update_fields=['status'])
    reservation = Reservation.objects.create(
        plot=plot, customer=customer, reservation_fee=Decimal('100000.00'),
        expiry_date=timezone.now() + timedelta(days=7), status=Reservation.Status.CANCELLED,
    )
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-list'), {
        'reservation': str(reservation.id), 'sale_type': Sale.SaleType.CASH,
        'sale_price': '20000000.00', 'down_payment': '20000000.00', 'payment_method': 'cash',
    })
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_cancel_reverts_plot_to_available(api_client, agent, plot, customer):
    plot.status = Plot.Status.SOLD
    plot.owner = customer
    plot.save(update_fields=['status', 'owner'])
    sale = Sale.objects.create(
        plot=plot, customer=customer, sale_type=Sale.SaleType.CASH,
        sale_price=Decimal('20000000.00'), down_payment=Decimal('20000000.00'),
    )
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-cancel', args=[sale.id]))
    assert response.status_code == status.HTTP_200_OK
    sale.refresh_from_db()
    plot.refresh_from_db()
    assert sale.status == Sale.Status.CANCELLED
    assert sale.cancelled_at is not None
    assert plot.status == Plot.Status.AVAILABLE
    assert plot.owner_id is None


@pytest.mark.django_db
def test_cancel_rejects_already_cancelled_sale(api_client, agent, sale):
    sale.status = Sale.Status.CANCELLED
    sale.save(update_fields=['status'])
    api_client.force_authenticate(user=agent)

    response = api_client.post(reverse('sale-cancel', args=[sale.id]))
    assert response.status_code == status.HTTP_400_BAD_REQUEST
