# Generated by Django 6.0.7 on 2026-07-29 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_grant_managing_director_edit_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_number', models.CharField(max_length=50)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('polygon_geojson', models.JSONField(blank=True, default=dict)),
                ('corner_coordinates', models.JSONField(blank=True, default=list)),
                ('google_maps_url', models.URLField(blank=True)),
                ('nearby_schools', models.JSONField(blank=True, default=list)),
                ('nearby_roads', models.JSONField(blank=True, default=list)),
                ('nearby_hospitals', models.JSONField(blank=True, default=list)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('images_360_urls', models.JSONField(blank=True, default=list)),
                ('current_owner', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('set_plot_financials', 'Can set plot price and discount')],
                'constraints': [models.UniqueConstraint(fields=('project', 'plot_number'), name='unique_plot_number_per_project')],
            },
        ),
    ]
