# Generated by Django 6.0.7 on 2026-08-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_lost_reason'),
        ('plots', '0002_grant_plot_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='current_owner',
        ),
        migrations.AddField(
            model_name='plot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_plots', to='crm.customer'),
        ),
    ]
